apiVersion: v2
name: helm-charts-oci-proxy
description: Transparently proxy and transform Chart Repository styled Helm Charts as OCI artifacts. Now you can address any public Chart Repository styled Helm Chart as an OCI image.
type: application
version: 1.2.4
# THis is a comment
appVersion: "a3a35bc"
home: https://github.com/container-registry/helm-charts-oci-proxy
icon: https://avatars.githubusercontent.com/u/46576199?s=200&v=4
keywords:
  - Helm Proxy
  - OCI Proxy
  - Helm Chart Proxy
sources:
  - https://github.com/container-registry/helm-charts-oci-proxy
maintainers:
  - name: 8gears Container Registry

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: "Replace deprecated Horizontal Pod Autoscaler version v2beta1 with v2. Requires Kubernetes v1.23+."
      links:
        - name: GitHub PR
          url: https://github.com/container-registry/helm-charts-oci-proxy/pull/12
