name: Helm Chart Validation

on:
  push:
    branches: [main]
    paths:
      - "chart/**"
  pull_request:
    branches: [main]
    paths:
      - "chart/**"

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: "latest"

      - name: Lint Helm Chart
        run: helm lint ./chart

      - name: Validate Structure with Template
        run: |
          helm template ./chart
          echo "✅ Helm chart structure is valid"
